=== ahm0xc/simsom/packages/config/src/app.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "tagline": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "emails": {
      "type": "object",
      "properties": {
        "primary": {
          "type": "string"
        },
        "support": {
          "type": "string"
        }
      }
    },
    "urls": {
      "type": "object",
      "properties": {
        "website": {
          "type": "string"
        },
        "github": {
          "type": "string"
        },
        "twitter": {
          "type": "string"
        }
      },
      "required": []
    },
    "native": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "slug": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "scheme": {
          "type": "string"
        }
      },
      "required": ["name", "slug", "version", "scheme"]
    }
  },
  "required": [
    "name",
    "description",
    "tagline",
    "author",
    "emails",
    "urls",
    "native"
  ]
}

=== ahm0xc/simsom/packages/config/src/app.json
{
  "$schema": "./app.schema.json",
  "name": "SimSom",
  "description": "SimSom is a social media platform that allows you to share your thoughts and ideas with the world.",
  "tagline": "Do small, do often",
  "author": "ahm0xc",
  "emails": {
    "primary": "simsom@gmail.com",
    "support": "support@simsom.com"
  },
  "urls": {},
  "native": {
    "name": "SimSom",
    "slug": "simsom",
    "version": "1.0.0",
    "scheme": "simsom"
  }
}
